version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - one_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - one_static:/data/static/
      - one_media:/data/media/

  django:
    image: ex01_django:4
    networks:
      - one_network
    volumes:
      - one_static:/home/django_ex01/staticfiles/
      - one_media:/home/django_ex01/media
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - one_network
    volumes:
      - ex01_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234

networks:
  one_network:

volumes:
  one_static:
  one_media:
  ex01_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true