version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - one_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - one_static:/data/static/
      - one_media:/data/media/

  django:
    image: one_django:3
    networks:
      - one_network
    volumes:
      - one_static:/home/django_ex01/staticfiles/
      - one_media:/home/django_ex01/media


networks:
  one_network:

volumes:
  one_static:
  one_media: