version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        target: 80
        published: 80
        protocol: tcp
    networks:
      - one_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - one_static:/data/static/
      - one_media:/data/media/
      - one_log:/var/log/nginx/
    secrets:
      - NGINX_AUTH

  goaccess:
    image: allinurl/goaccess:1.5.1
    ports:
      - 7890:7890
    volumes:
      - one_log:/var/log/nginx/ #volumes 로그코드
    command: /var/log/nginx/ex01_access.log -o /var/log/nginx/report.html
    --real-time-html --log-format COMBINED

  django:
    image: ex01_django:5
    networks:
      - one_network
    volumes:
      - one_static:/home/django_ex01/staticfiles/
      - one_media:/home/django_ex01/media
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - one_network
    volumes:
      - ex01_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD

networks:
  one_network:

volumes:
  one_static:
  one_media:
  ex01_mariadb:
  one_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true